name: Publish Package to github NPM registry
on: 
  release:
    types: [published, edited] 
jobs:
  test-publish-packages:
      runs-on: ubuntu-latest
      permissions:
        packages: write
        contents: read
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Setup nodejs version - 20.x
        uses: actions/setup-node@v4
        with:
            node-version: 20.x
            registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm install

      - name: Publish to Github registry
        run: npm publish
        env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}